---
abstract: 'Force running a specific tool at regular intervals.'
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  Git::Repository: '0'
  Test::Exception: '0'
  Test::FailWarnings: '0'
  Test::More: '0.94'
  Test::Requires::Git: '1.005'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-GitHooks-Plugin-ForceRegularUpdate
provides:
  App::GitHooks::Plugin::ForceRegularUpdate:
    file: lib/App/GitHooks/Plugin/ForceRegularUpdate.pm
    version: v1.0.4
requires:
  App::GitHooks: '0'
  Carp: '0'
  File::Slurp: '0'
  perl: '5.01'
resources:
  bugtracker: https://github.com/guillaumeaubert/App-GitHooks-Plugin-ForceRegularUpdate/issues
  homepage: https://metacpan.org/release/App-GitHooks-Plugin-ForceRegularUpdate
  license: http://www.gnu.org/licenses/gpl-3.0.txt
  repository: https://github.com/guillaumeaubert/App-GitHooks-Plugin-ForceRegularUpdate
version: v1.0.4
